---

- name: Ensure Homebrew Taps.
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - caskroom/drivers
    - caskroom/fonts
    - caskroom/versions
    - buo/cask-upgrade

- name: Install app casks.
  homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items:
    - docker
    - git
    - go
    - google-chrome
    - jetbrains-toolbox
    - slack
    - virtualbox
    - vlc
    - whatsapp
    - ipcalc
    - nvm
    - packer
    - terraform
    - tfswitch
    - tree
    - wget
    - kt2f
    - consul
    - kubernetes-cli
    

- name: Accept Xcode license.
  shell: xcodebuild -license accept
  become: true
