---

- name: Ensure Homebrew Taps.
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - caskroom/drivers
    - caskroom/fonts
    - caskroom/versions
    - buo/cask-upgrade

- name: Install app casks.
  homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items:
    - consul
    - docker
    - git
    - go
    - google-chrome
    - jetbrains-toolbox
    - ipcalc # calculate various network subnet masks etc., from a given ip address
    - kt2f # kubernetes yml to terraform convertor (https://github.com/sl1pm4t/k2tf)
    - kubernetes-cli
    - nvm
    - packer
    - python # installs latest version of python including pip
    - ruby
    - slack
    - terraform
    - tfswitch # switch between different versions of terraform (https://tfswitch.warrensbox.com/)
    - tree
    - virtualbox
    - vlc
    - wget
    - whatsapp
    
- name: Install aws cli
  shell: pip install --upgrade awscli
  
- name: Accept Xcode license.
  shell: xcodebuild -license accept
  become: true
 
